#!/usr/bin/env python

import sys
from nirvana.nirvana import Nirvana

if __name__ == '__main__':
    # Usage: nirvana <username> <md5 of password>
    print "Authenticating..."
    nirv = Nirvana(username=sys.argv[1], password_md5=sys.argv[2])
    nirv.authenticate()

    print "Authenticated {0} {1}! Auth token: {2}".format(
            nirv.user.firstname, nirv.user.lastname, nirv.auth_token)
